### PR TITLE
add tests for camelCase function

### PR DESCRIPTION
**Pull request by austinpray**
- [ ] make the tests pass

this is a choose your own adventure game:
- fix your method
- [use lodash.camelcase](https://github.com/roots/js-dom-router/pull/3)
- [vendor lodash.camelcase](https://github.com/roots/js-dom-router/pull/4)

### CODE REVIEW

**Comment by austinpray** [comment]
```

  camelCase
    1) should generally work
    2) should work with numbers
    3) should handle acronyms


  0 passing (8ms)
  3 failing

  1) camelCase
       should generally work:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'fOOBAR'
- 'fooBar'
      + expected - actual

      -fOOBAR
      +fooBar
      
      at /home/austin/Projects/roots/js-dom-router/test/camelCase.test.js:10:14
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (test/camelCase.test.js:9:7)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  2) camelCase
       should work with numbers:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'enable6hFormat'
- 'enable6HFormat'
          ^
      + expected - actual

      -enable6hFormat
      +enable6HFormat
      
      at Context.<anonymous> (test/camelCase.test.js:17:12)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)

  3) camelCase
       should handle acronyms:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'safeHTML'
- 'safeHtml'
        ^
      + expected - actual

      -safeHTML
      +safeHtml
      
      at /home/austin/Projects/roots/js-dom-router/test/camelCase.test.js:26:14
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (test/camelCase.test.js:25:31)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)





```

**Comment by QWp6t** [comment]
I appreciate that you've added tests, but...

Why would it need to escape HTML entities?
Why would need to support capital letters?
Why does it need to work with spaces?

See: https://github.com/roots/js-dom-router/blob/master/Router.js#L50-L53

**Comment by swalkinshaw** [comment]
Use what we have or just vendor https://github.com/sindresorhus/camelcase/blob/master/index.js

lodash's version is insane

**Comment by swalkinshaw** [comment]
Here's another idea: just don't camelCase! hyphen keys work fine in JS

**Comment by austinpray** [comment]
@swalkinshaw 
> Use what we have

what we have has undefined behavior for lots of common input

> just vendor

https://github.com/roots/js-dom-router/pull/4

>Here's another idea: just don't camelCase! hyphen keys work fine in JS

image
I think we are there.

> lodash's version is insane

if unicode didn't exist and you only had to camelcase text with ascii alpha characters this would be true

**Pull request closed without merging**
